//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldBunny.basedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medcard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medcard()
        {
            this.Pet = new HashSet<Pet>();
        }
    
        public int IDMedcard { get; set; }
        public int DiagnosisID { get; set; }
        public System.DateTime StartIlness { get; set; }
        public System.DateTime EndIlness { get; set; }
        public int RecipeListID { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual RecipeList RecipeList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet> Pet { get; set; }
    }
}
